Feature/user service work
kampaii53/jdbc-example pull request #10
Opened 2024-06-18 01:39 UTC by brominchic

выносим singleThreadExecution в сервис UserService - интерфейс должен предоставлять метод создания пользователя с определенным именем и определенным количеством счетов. первая имплементация оставит в стандартном виде singleThread. вторая - в транзакционном. тест переписываем на использование имплементаций сервиса а не репозиториев напрямую.

добавляем для каждой имплементации unit-test

задание со звездочкой - предложить варианты еще больше ускорить вставку

2024-06-18 20:11 UTC, kampaii53 requested changes

2024-06-18 20:11 UTC, kampaii53 commented on src/main/java/ru/kampaii/examples/repositories/Repository.java
> +
формат загулял

2024-06-18 20:11 UTC, kampaii53 commented on src/main/java/ru/kampaii/examples/repositories/Repository.java
> +                        insert += data.get(namesOfStrings.get(j)) + ",";
давай тоже через prepared

2024-06-18 20:11 UTC, kampaii53 commented on src/main/java/ru/kampaii/examples/repositories/servises/Service.java
> +public interface Service <T extends Entity> {
женериков не надо, просто userService

2024-06-18 20:11 UTC, kampaii53 commented on src/test/ru/kampaii/examples/repositories/EntityAndRepositoryImplTest.java
> +    // отрабатывает 5 минут у Тимура
комменты уже не актуальные

2024-06-18 20:11 UTC, kampaii53 commented on src/test/ru/kampaii/examples/repositories/EntityAndRepositoryImplTest.java
> +package ru.kampaii.examples.repositories;
а чего тест вдруг из java папки убежал

2024-06-18 20:11 UTC, kampaii53 commented on src/test/ru/kampaii/examples/repositories/EntityAndRepositoryImplTest.java
> +    void userServiceTest() throws SQLException {
тесты относящиеся к userService - в отдельный тестовый класс

2024-06-18 20:14 UTC, brominchic commented on src/test/ru/kampaii/examples/repositories/EntityAndRepositoryImplTest.java
> +package ru.kampaii.examples.repositories;
у меня писал мол prohibited path

2024-06-25 07:05 UTC, kampaii53 commented on src/main/java/ru/kampaii/examples/repositories/servises/UserServiceTransactionalBatch.java
> +                accountsRepository.create(new AccountsEntity(null, (float) random.nextInt(0, 10000), 1, userId));
я имел в виду, вот тут батч должен использоваться

2024-06-25 07:05 UTC, kampaii53 commented on src/test/ru/kampaii/examples/repositories/UserServicesTest.java
> +        usersRepository = Mockito.mock(UsersRepositoryImpl.class);
unit-тест для каждого класса пишется в отдельном тест-классе, не перемешивай их в одном классе с интеграционным

2024-06-30 10:29 UTC, kampaii53 requested changes

2024-06-30 10:29 UTC, kampaii53 commented on src/test/ru/kampaii/examples/repositories/UserServicesTest.java
> +        usersRepository = new UsersRepositoryPreparedImpl(connection, new PooledIdGeneratorImpl(connection, "users", "id", 1, 1000));
если инициализация повторяется - запихни в beforeEach

2024-06-30 10:29 UTC, kampaii53 commented on src/test/ru/kampaii/examples/repositories/UsersServiceTransactionalBatchTest.java
> +    private Repository<UsersEntity, Integer> usersRepository;
попробуй в нит тестах воспользоваться аннотациями @Mock / @InjectMocks

2024-06-30 10:29 UTC, kampaii53 commented on src/test/ru/kampaii/examples/repositories/UsersServiceTransactionalBatchTest.java
> +        assertEquals(name, entity.getName());
счета после возврата тоже надо проверить

2024-06-30 15:27 UTC, brominchic commented on src/test/ru/kampaii/examples/repositories/UserServicesTest.java
> +        usersRepository = new UsersRepositoryPreparedImpl(connection, new PooledIdGeneratorImpl(connection, "users", "id", 1, 1000));
там же разные usersRepositoryImpl

2024-06-30 15:36 UTC, brominchic commented on src/test/ru/kampaii/examples/repositories/UsersServiceTransactionalBatchTest.java
> +        assertEquals(name, entity.getName());
а как их проверить если user service не возвращает счета

2024-06-30 18:59 UTC, kampaii53 requested changes

2024-06-30 18:59 UTC, kampaii53 commented on src/test/ru/kampaii/examples/repositories/UsersServiceTransactionalBatchTest.java
> +        assertEquals(name, entity.getName());
должен возвращать внутри entity же

2024-06-30 18:59 UTC, kampaii53 commented on src/test/ru/kampaii/examples/repositories/UserServicesTest.java
> +@ExtendWith(MockitoExtension.class)
при чем тут мокито

2024-07-02 13:02 UTC, kampaii53 approved these changes

2024-07-02 17:18 UTC, merged